name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Configure Gradle for optimal use in GiHub Actions, including caching of downloaded dependencies.
      # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5

      - name: Build with Gradle
        run: gradle jar

      - name: Save SendingWithAcks JAR
        uses: actions/upload-artifact@v4.3.1
        with:
          name: SendingWithAcksJava-5784.jar
          path: SendingWithAcksJava/build/libs
          retention-days: 30

      - name: Save UdpStopWaitClient JAR
        uses: actions/upload-artifact@v4.3.1
        with:
          name: UdpStopWaitClient-5784.jar
          path: UdpStopWaitClient/build/libs
          retention-days: 30

      - name: Save UdpStopWaitServer JAR
        uses: actions/upload-artifact@v4.3.1
        with:
          name: UdpStopWaitServer-5784.jar
          path: UdpStopWaitServer/build/libs
          retention-days: 30

      - name: Complete sending with acks calculations
        run: |
          cp SendingWithAcksJava/build/libs/SendingWithAcksJava-5784.jar .
          chmod 700 sending-with-acks-tests.bat
          ./sending-with-acks-tests.bat

      - name: Summarize sending with acks results
        uses: actions/upload-artifact@v4.3.1
        with:
          name: sending-with-acks-tests-results
          path: sending-with-acks-tests-results.txt
          retention-days: 30

      - name: Complete sending with acks actual
        run: |
          cp UdpStopWaitClient/build/libs/UdpStopWaitClient-5784.jar .
          cp UdpStopWaitServer/build/libs/UdpStopWaitServer-5784.jar .
          mkdir outfiles
          chmod 700 stop-wait-tests.bat
          ./stop-wait-tests.bat

      - name: Save outfiles and sha256sum results
        uses: actions/upload-artifact@v4.3.1
        with:
          name: outfiles
          path: outfiles/
          retention-days: 30

      - name: Save client output
        uses: actions/upload-artifact@v4.3.1
        with:
          name: client-output
          path: ./test*-client-output.txt
          retention-days: 30

      - name: Save server output
        uses: actions/upload-artifact@v4.3.1
        with:
          name: server-output
          path: test*-server-output.txt
          retention-days: 30

      - name: generate javadoc
        run: gradle javadoc

      - name: Save SendingWithAcks Javadoc
        uses: actions/upload-artifact@v4.3.1
        with:
          name: SendingWithAcks-Javadoc
          path: SendingWithAcksJava/build/docs/javadoc
          retention-days: 30

      - name: Save UdpStopWaitClient Javadoc
        uses: actions/upload-artifact@v4.3.1
        with:
          name: UdpStopWaitClient-Javadoc
          path: UdpStopWaitClient/build/docs/javadoc
          retention-days: 30

      - name: Save UdpStopWaitServer Javadoc
        uses: actions/upload-artifact@v4.3.1
        with:
          name: UdpStopWaitServer-Javadoc
          path: UdpStopWaitServer/build/docs/javadoc
          retention-days: 30

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
